import * as fs from 'fs';
import * as path from 'path';

const NOTES_DIR = path.join(__dirname, '../../apps/notebook-llc/engineering-notes');

// Ensure directory exists
if (!fs.existsSync(NOTES_DIR)) {
  fs.mkdirSync(NOTES_DIR, { recursive: true });
}

const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
const noteFileName = `eng-note-${timestamp}.md`;
const notePath = path.join(NOTES_DIR, noteFileName);

const template = `---
type: engineering-note
date: ${new Date().toISOString()}
author: Antigravity
status: Automatic
---

# Engineering Note: ${timestamp}

## Change Summary
- [Describe changes here]

## Technical Details
- Analysis of recent changes.
- Generated by Antigravity Automation.

## Next Steps
- Review deployment logs.
`;

fs.writeFileSync(notePath, template);
console.log(`[Notebook LLC] Created new Engineering Note: ${notePath}`);
